# -*- coding: utf-8 -*-
"""Exercise 4: Rivers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qxDDA3GASDb70wsCFg6W4xw7QMcol7W3
"""

# a dictionary containing three major rivers and the country each river runs through. One key-value pair might be 'nile': 'egypt'.

#Use a loop to print a sentence about each river, such as The Nile runs through Egypt.

#Use a loop to print the name of each river included in the dictionary.

#Use a loop to print the name of each country included in the dictionary.

rivers = {
    "Cagayan" : "Philippines",
    "mississippi" : "united states",
    "Amazon" : "South America",
    "Mekong" : "Vietnam",
    "Congo" : "Republic of the Congo",
    }

for river, country in rivers.items():
    print("The " + river.title() + " flows through " + country.title() + ".")

print("\nThe following rivers around the world are included in this data set:")
for river in rivers.keys():
    print("- " + river.title())

print("\nThese countries are included in this data set:")
for country in rivers.values():
    print("- " + country.title())