# -*- coding: utf-8 -*-
"""Exercise 1: Person

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qxDDA3GASDb70wsCFg6W4xw7QMcol7W3
"""

#Use a dictionary to store information about a person you know.Store their first name, last name, age, and the city in which they live. You

#should have keys such as first_name, last_name, age, and city. Print each piece of information stored in your dictionary.

information = {"first_name" : "Angela", "last_name" : "Villapaz", "city" : "Bulacan City"}

print(information["first_name"])

print(information["last_name"])

print(information["city"])