# -*- coding: utf-8 -*-
"""Chapter 6 Exercise 1: Pizza Toppings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18RgXnyjR2sGOpRNDm2Lr8gkSZ0x_tVX7
"""

#Write a loop that prompts the user to enter a series of pizza toppings until they enter a 'quit' value. As they enter each topping,

#print a message saying you’ll add that topping to their pizza.

prompt = "\nHello, good day! What topping would you like on your pizza?"
prompt += "\nEnter 'quit' when you are finished: "


while True:
    topping = input(prompt)
    if topping != 'quit':
        print("  I'll add " + topping + " to your pizza.")
    else:
        break