# -*- coding: utf-8 -*-
"""Chapter 6 Exercise 3: Infinity

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18RgXnyjR2sGOpRNDm2Lr8gkSZ0x_tVX7
"""

#Write a loop that never ends, and run it. (To end the loop, press ctrl-C or close the window displaying the output.)

while True:
  print("I love you")