# -*- coding: utf-8 -*-
"""Chapter 7 Exercise 1: Message

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Re9MyWoee0W_QhOEnro9ToblxFMydgHv
"""

#Write a function called display_message() that prints one sentence telling everyone what you are learning about in this chapter. Call the

#function, and make sure the message displays correctly.

def display_message():
    """Display a message about what I'm learning."""
    msg = "I'm learning how to use functions in python."
    print(msg)

display_message()