# -*- coding: utf-8 -*-
"""Chapter 7 Exercise 3: T-shirt

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Re9MyWoee0W_QhOEnro9ToblxFMydgHv
"""

#Write a function called make_shirt() that accepts a size and the text of a message that should be printed on the shirt. The function

#should print a sentence summarizing the size of the shirt and the message printed on it. Call the function once using positional

#arguments to make a shirt. Call the function a second time using keyword arguments.

def make_shirt(size, message):
    """Summarize the shirt that's going to be made."""
    print("\nI'm going to produce a " + size + " t-shirt.")
    print('It will say, "' + message + '"')

make_shirt("large", "I love You!")
make_shirt(message="You're are important", size="medium")