# -*- coding: utf-8 -*-
"""Chapter 7 Exercise 2: Favorite Book

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Re9MyWoee0W_QhOEnro9ToblxFMydgHv
"""

#Write a function called favorite_book() that accepts one parameter, title. The function should print a message, such as One of my

#favorite books is Alice in Wonderland. Call the function, making sure to include a book title as an argument in the function call.

def favorite_book(title):
    """Display a message about someone's favorite book."""
    print(title + " is one of my favorite books.")

favorite_book("The Purpose Driven Life")