# -*- coding: utf-8 -*-
"""Chapter 4: Exercise 2 alien colors #2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-iXRhGJAAprgKrGYkfiB5UAvykcVs2C
"""

#Choose a color for an alien as you did in Exercise 5-3, and write an if-else chain.

#•If the alien’s color is green, print a statement that the player just earned 5 points for shooting the alien.

#•If the alien’s color isn’t green, print a statement that the player just earned 10 points.

#•Write one version of this program that runs the if block and another that runs the else block.

alien_color = "green"

if alien_color == "green":
  print("Congratulations, you have earned 5 points")

else:
  print("Congratulations, you have earned 10 points")

#Choose a color for an alien as you did in Exercise 5-3, and write an if-else chain.

#•If the alien’s color is green, print a statement that the player just earned 5 points for shooting the alien.

#•If the alien’s color isn’t green, print a statement that the player just earned 10 points.

#•Write one version of this program that runs the if block and another that runs the else block.

alien_color = "yellow"

if alien_color == "green":
  print("Congratulations, you have earned 5 points")

else:
  print("Congratulations, you have earned 10 points")