# -*- coding: utf-8 -*-
"""Chapter 4: Exercise 1 alien colors #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-iXRhGJAAprgKrGYkfiB5UAvykcVs2C
"""

#Imagine an alien was just shot down in a game. Create a variable called alien_color and assign it a value of 'green', 'yellow', or 'red'.

#•Write an if statement to test whether the alien’s color is green. If it is, print a message that the player just earned 5 points.

#•Write one version of this program that passes the if test and another that fails. (The version that fails will have no output.)

#PART 1

alien_color = "green"

if alien_color == "green":
  print("Congratulations, you have earned 5 points")

#Imagine an alien was just shot down in a game. Create a variable called alien_color and assign it a value of 'green', 'yellow', or 'red'.

#•Write an if statement to test whether the alien’s color is green. If it is, print a message that the player just earned 5 points.

#•Write one version of this program that passes the if test and another that fails. (The version that fails will have no output.)

#PART 1

alien_color = "red"

if alien_color == "green":
  print("Congratulations, you have earned 5 points")