# -*- coding: utf-8 -*-
"""Chapter 4: Exercise 5 favorite fruit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-iXRhGJAAprgKrGYkfiB5UAvykcVs2C
"""

#Make a list of your favorite fruits, and then write a series of independent if statements that check for certain fruits in your list.

#•Make a list of your three favorite fruits and call it favorite_fruits.

#•Write five if statements. Each should check whether a certain kind of fruit is in your list. If the fruit is in your list, the if block

#should print a statement,such as You really like bananas!

fav_fruits = ["blueberries", "apple", "orange", "mango"]

if "bananas" in fav_fruits:
    print("You really like kiwis!")
if "apples" in fav_fruits:
    print("You really like apples!")
if "blueberries" in fav_fruits:
    print("You really like blueberries!")
if "kiwis" in fav_fruits:
    print("You really like banana!")
if "peaches" in fav_fruits:
    print("You really like grapes!")