# -*- coding: utf-8 -*-
"""Chapter 3 Exercise 4 Guest list

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oaLiT6G5KxX3BJY-f_8zx2Jdlzzh0EVz
"""

#If you could invite anyone, living or deceased, to dinner, 
#who would you invite? Make a list that includes at least three people you’d
#like to invite to dinner. Then use your list to print a message to each person, 
#invitingthem to dinner.

dinner_guests = ["Angela","Kirby","James"]

print("Hey",dinner_guests[0],"If you're free tonight would you perhaps want to go on a dinner date with me? love you <3")
print("Good day to you",dinner_guests[1],"I would like to invite you to a dinner that I would be hosting")
print("Good day to you",dinner_guests[2],"I would like to invite you to a dinner that I would be hosting")